version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  importer:
    build: ./scraper
    command: npm start
    depends_on:
      - db

  backend:
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - db
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  postgres_data:
